# 0 is only for cancellation so keep it at origin
0:
  position:
    x: 0.0
    y: 0.0
  orientation:
    x: 0.0
    y: 0.0
    z: 0.0
    w: 1.0

# Bottom Left Yaskawa arm
1:
  position:
    x: 1.0
    y: -1.6
  orientation:
    x: 0.0
    y: 0.0
    z: 0.039543246
    w: 0.999056608

# In between two tables
2:
  position:
    x: 5.6647961
    y: -0.2252817798096
  orientation:
    x: 0.0
    y: 0.0
    z: -0.7055296
    w: -0.7055296

# For John and Dimi (Bottom right table adjacent)
3:
  position:
    x: -2.6391864
    y: 0.54888858
  orientation:
    x: 0.0
    y: 0.0
    z: 0.00974890
    w: 0.99951342

# Bottom Right Yaskawa arm
4:
  position:
    x: -0.892079
    y: -1.268178
  orientation:
    x: 0.0
    y: 0.0
    z: 0.9998668
    w: -0.004333


# Top Right Table (potential stockroom)
5:
  position:
    x: -0.931096
    y: -5.244719
  orientation:
    x: 0.0
    y: 0.0
    z: 0.712658213
    w: 0.701327674
